Repository boolean-uk/team-dev-client-team-3, pull requests merged in 2025-09, with the labels that each got.

#41 Issue(#23): Added step two to Create Profile and moved step four
  src/pages/welcome/index.js
  src/pages/welcome/stepFour/index.js
  src/pages/welcome/stepTwo/index.js
Labels: Frontend

#78 Register: Validation of password and email with backend, and a refactor.
  src/pages/register/index.js
  src/pages/register/registrationValidation.js
  src/service/apiValidation.js
Labels: enhancement, Frontend

#90 (Issue#89): Fixed NaN when posting (+ some other minor stuff)
  src/components/createPostModal/index.js
  src/components/editPostModal/index.js
  src/components/header/index.js
  src/components/post/index.js
  src/components/post/style.css
  src/components/posts/index.js
  src/context/auth.js
  src/pages/dashboard/index.js
Labels: enhancement, Frontend

#88 Issue(#32): Validation of usernames in Create Profile Step 1
  src/components/form/textInput/index.js
  src/components/stepper/index.js
  src/pages/welcome/index.js
  src/pages/welcome/stepOne/index.js
  src/pages/welcome/style.css
  src/pages/welcome/welcomeValidation.js
  src/service/apiValidation.js
Labels: Frontend

#109 Issue(#68): Created a component that displays all other users in the userss cohort.
  src/components/avatarList/index.jsx
  src/components/avatarList/singleLineListItem/index.jsx
  src/components/avatarList/singleLineListItem/style.css
  src/components/avatarList/style.css
  src/pages/dashboard/index.js
  src/pages/dashboard/testData.jsx
Labels: Frontend

#167 Linter Config: Fix so that it actually lints whitespace.
  .eslintrc.json
  package.json
  src/components/loader/Loader.jsx
  src/pages/cohort/CohortPage.jsx
  src/pages/profile/ProfilePage.jsx
Labels: enhancement, Chore

#230 A couple of expects should be awaited
  test/helpers.ts
  test/profilePage.spec.ts
Labels: Chore, tests

#257 Added regex for phonenumber on registration.
  src/components/stepper/index.js
  src/pages/welcome/index.js
  src/pages/welcome/stepContact/index.js
  src/pages/welcome/welcomeValidation.js
Labels: enhancement
