Repository boolean-uk/team-dev-client-team-3, pull requests merged in 2025-08, with the labels that each got.

#15 Issue(#14): Added ESlint rule.
  .eslintrc.json
Labels: Chore

#28 Issue(#27): Moved `Forgot password?`-link from textinput to loginview.
  src/components/form/textInput/index.js
  src/pages/login/index.js
Labels: bug, Frontend

#21 Added text info on register page. Closing issue #8
  src/pages/register/index.js
  src/pages/register/register.css
  src/styles/_globals.css
Labels: Frontend
